### ISSUE TITLE
Layout settings not accepting 0 value

### ISSUE THREAD

**Issue by AlexNorb** [foosel/cardfoldr#14]
### Please describe the problem you are facing.

The layout settings does not seem to accept 0 as a value. If 0 is entered it ignores it and reverts to default (?). 
This is not an issue for printer margin since that should never be 0. 
For card/fold margin it is sometimes wanted to have it set to 0.

Current workaround is to set value to 0.1

**Comment by foosel** [comment]
Ah, I'm pretty sure what's going on there and will see that I fix it asap. Thanks for reporting! 👍
